# Generated by Django 4.2.21 on 2025-06-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_type',
            field=models.CharField(default="Driver's License", max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Civilian Employee', 'Civilian Employee'), ('Military Personnel', 'Military Personnel'), ('Contractor', 'Contractor')], default='Civilian Employee', max_length=50),
        ),
    ]
