# Generated by Django 4.2.21 on 2025-06-05 18:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_birth_date_user_id_image_user_id_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_image',
        ),
        migrations.AddField(
            model_name='equipment',
            name='qr_string',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
